// common/constants/error-codes.ts

export const ErrorCodes = {
  // parking related errors
  PARKING_CLAIM_ERROR: 'PARKING_CLAIM_ERROR',
  // Validation Errors (400 range)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_STATE: 'INVALID_STATE',

  // Authentication Errors (401, 403)
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // Resource Errors (404)
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Conflict Errors (409)
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Server Errors (500 range)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

  UNIQUE_VIOLATION: 'UNIQUE_VIOLATION',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  NOT_NULL: 'NOT_NULL',
  INVALID_TEXT_REPRESENTATION: 'INVALID_TEXT_REPRESENTATION',

  PAYMENT_SERVICE_ERROR: 'PAYMENT_SERVICE_ERROR',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  HTTP_EXCEPTION:'HTTP_EXCEPTION',
  NOTIFICATION_ERROR: 'NOTIFICATION_ERROR'
} as const;
