// 

function bit(n: number): bigint {
  return 1n << BigInt(n);
}

export const Permissions = {
  // USER (0–12)
  USER_CREATE: bit(0),
  USER_READ: bit(4),
  USER_WRITE: bit(8),
  USER_DELETE: bit(12),

  // PARKING PROPERTY (16–28)
  PARKING_PROPERTY_READ: bit(16),
  PARKING_PROPERTY_UPDATE: bit(20),
  PARKING_PROPERTY_DELETE: bit(24),
  PARKING_PROPERTY_CREATE: bit(28),

  // PARKING OWNER (32–44)
  PARKING_OWNER_CREATE: bit(32),
  PARKING_OWNER_READ: bit(36),
  PARKING_OWNER_UPDATE: bit(40),
  PARKING_OWNER_DELETE: bit(44),

  // PARKING BOOKING (48–64)
  PARKING_BOOKING_CREATE: bit(48),
  PARKING_BOOKING_READ_ONE: bit(52),
  PARKING_BOOKING_UPDATE: bit(56),
  PARKING_BOOKING_DELETE: bit(60),
  PARKING_BOOKING_READ_ALL: bit(64),

  // CLAIM PARKING PROPERTY (68–80)
  CLAIM_PARKING_PROPERTY_CREATE: bit(68),
  CLAIM_PARKING_PROPERTY_READ: bit(72),
  CLAIM_PARKING_PROPERTY_UPDATE: bit(76),
  CLAIM_PARKING_PROPERTY_DELETE: bit(80),

  // INVOICE (84–96)
  INVOICE_CREATE: bit(84),
  INVOICE_READ: bit(88),
  INVOICE_UPDATE: bit(92),
  INVOICE_DELETE: bit(96),

  // PARTNER (100–112)
  PARTNER_CREATE: bit(100),
  PARTNER_READ: bit(104),
  PARTNER_UPDATE: bit(108),
  PARTNER_DELETE: bit(112),

  // COUPON (116–136)
  COUPON_CREATE: bit(116),
  COUPON_READ: bit(120),
  COUPON_UPDATE: bit(124),
  COUPON_DELETE: bit(128),
  COUPON_READ_ALL: bit(132),
  COUPON_READ_BY_CODE: bit(136),

  // RATINGS (140–152)
  RATINGS_CREATE: bit(140),
  RATINGS_READ: bit(144),
  RATINGS_UPDATE: bit(148),
  RATINGS_DELETE: bit(152),

  // WATCHMAN (156–168)
  WATCHMAN_CREATE: bit(156),
  WATCHMAN_READ: bit(160),
  WATCHMAN_UPDATE: bit(164),
  WATCHMAN_DELETE: bit(168),

  // SUPER ADMIN API ACL (172–224)
  PARKING_ADMIN_GET_STATS: bit(172),
  PARKING_ADMIN_GET_BOOKINGS: bit(176),
  PARKING_ADMIN_GET_BOOKING_BY_ID: bit(180),
  PARKING_ADMIN_UPDATE_BOOKING: bit(184),
  PARKING_ADMIN_GET_PARKING_OWNER: bit(188),
  PARKING_ADMIN_GET_PARKING_CUSTOMERS: bit(192),
  PARKING_ADMIN_PATCH_PARKING_PROPERTY: bit(196),
  PARKING_ADMIN_PUT_PARKING_PROPERTY: bit(200),
  PARKING_ADMIN_PATCH_PARKING_OWNER: bit(204),
  PARKING_ADMIN_GET_PROPERTY_CLAIM: bit(208),
  PARKING_ADMIN_GET_PROPERTY_CLAIM_BY_ID: bit(212),
  PARKING_ADMIN_PATCH_PROPERTY_CLAIM: bit(216),
  PARKING_ADMIN_DELETE_PROPERTY_CLAIM: bit(220),

  // PARKING OWNER API ACL (224–252)
  PARKING_OWNER_GET_STATS: bit(224),
  PARKING_OWNER_POST_CLAIM_PARKING_PROPERTY: bit(228),
  PARKING_OWNER_GET_ALL_ASSOCIATED_CLAIM_PARKING_PROPERTY: bit(232),
  PARKING_OWNER_GET_ONE_ASSOCIATED_CLAIM_PARKING_PROPERTY: bit(236),
  PARKING_OWNER_UPDATE_ASSOCIATED_CLAIM_PARKING_PROPERTY: bit(240),
  PARKING_OWNER_REMOVE_ASSOCIATED_CLAIM_PARKING_PROPERTY: bit(244),
  PARKING_OWNER_GET_ALL_ASSOCIATED_PARKING_BOOKINGS: bit(248),
  PARKING_OWNER_GET_ONE_ASSOCIATED_PARKING_BOOKINGS: bit(252),

  // WATCHMAN API ACL (256–264)
  WATCHMAN_GET_ASSOCIATED_PARKING_BOOKINGS: bit(256),
  WATCHMAN_UPDATE_ASSOCIATED_PARKING_BOOKINGS: bit(260),

  // CUSTOMER API ACL (264–292)
  CUSTOMER_GET_ONE_PARKING_BOOKINGS: bit(264),
  CUSTOMER_UPDATE_PARKING_BOOKINGS: bit(268),
  CUSTOMER_STATS_PARKING_BOOKINGS: bit(272),
  CUSTOMER_PROCESS_PAYMENT: bit(276),
  CUSTOMER_GET_ALL_PAYMENT_TRANSACTIONS: bit(280),
  CUSTOMER_GET_ONE_PAYMENT_TRANSACTIONS: bit(284),
  CUSTOMER_GET_ALL_PARKING_BOOKINGS: bit(288),

  // CONSTANTS & MISC (292+)
  READ_CONSTANTS: bit(292),
  UPLOAD_DOCUMENT: bit(296),
};
